title: Dyno Custom Commands
repotitle: Dyno Custom Commands
author: The DCC Team
authorurl: https://dynocc.tk/staff
url: https://dynocc.tk
remote_theme: advaith1/architect
btfn_widget: true
favicon: files/dcc-trans.png
